export const ActionTypes={

    GET_TOKEN:'GET_TOKEN',
    GET_TOKEN_FAIL:'GET_TOKEN_FAIL',
    GET_TOKEN_SUCCESS:'GET_TOKEN_SUCCESS',

    REFRESH_TOKEN: 'REFRESH_TOKEN',
    REFRESH_TOKEN_FAIL: 'REFRESH_TOKEN_FAIL',
    REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',

    IDCHECK:'IDCHECK',
    IDCHECK_FAIL:'IDCHECK_FAIL',
    IDCHECK_SUCCESS:'IDCHECK_SUCCESS',

    EMAILCHECK:'EMAILCHECK',
    EMAILCHECK_FAIL:'EMAILCHECK_FAIL',
    EMAILCHECK_SUCCESS:'EMAILCHECK_SUCCESS',

    SIGNUP:'SIGNUP',
    SIGNUP_FAIL:'SIGNUP_FAIL',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',

    LOGIN:'LOGIN',
    LOGIN_FAIL:'LOGIN_FAIL',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',

    LOGOUT:'LOGOUT',

    GET_USERME:'GET_USERME',
    GET_USERME_SUCCESS:'GET_USERME_SUCCESS',
    
    //QnABoard 관련 
    LOAD_QNABOARDLIST:'LOAD_QNABOARDLIST',
    LOAD_QNABOARDLIST_SUCCESS:'LOAD_QNABOARDLIST_SUCCESS',
    WRITE_QNABOARD:'WRITE_QNABOARD',
    WRITE_QNABOARD_SUCCESS:'WRITE_QNABOARD_SUCCESS',
    QNABOARD_DELETE:'QNABOARD_WRITE',
    QNABOARD_EDIT:'QNABOARD_EDIT',
    QNABOARD_FAIL:'QNABOARD_FAIL',


    // 0810 loadProductList 
    LOAD_PRODUCTLIST : 'LOAD_PRODUCTLIST',
    LOAD_PRODUCTLIST_FAIL : 'LOAD_PRODUCTLIST_FAIL',
    LOAD_PRODUCTLIST_SUCCESS : 'LOAD_PRODUCTLIST_SUCCESS',

    // 0810 addCart
    ADD_CART : 'ADD_CART'
    // 필요한가..??
    // ADD_CART_FAIL: 'ADD_CART_FAIL',
    // ADD_CART_SUCCESS: 'ADD_CART_SUCCESS'

}